[project]
name = "Afisha"
version = "0.1.0"
description = ""
requires-python = ">=3.13"
dependencies = [
    "alembic==1.16.2",
    "asyncpg>=0.31.0",
    "fastapi==0.139.0",
    "granian[reload,uvloop]>=2.7.9",
    "httpx>=0.28.1",
    "pydantic-settings>=2.14.2",
    "redis>=8.0.1",
    "reportlab>=5.0.0",
    "sqlalchemy==2.0.41",
    "taskiq>=0.12.4",
    "taskiq-redis>=1.2.3",
    "tenacity>=9.1.4",
    "uvicorn[standard]==0.35.0",
]

[dependency-groups]
dev = [
    "ruff==0.12.2",
    "ty>=0.0.58",
]

[tool.ruff]
line-length = 120
