#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $AFISHA_DB_USER WITH ENCRYPTED PASSWORD '$AFISHA_DB_PASS';
    CREATE DATABASE $AFISHA_DB_NAME OWNER $AFISHA_DB_USER;

    CREATE USER $PURCHASED_TICKETS_DB_USER WITH ENCRYPTED PASSWORD '$PURCHASED_TICKETS_DB_PASS';
    CREATE DATABASE $PURCHASED_TICKETS_DB_NAME OWNER $PURCHASED_TICKETS_DB_USER;
EOSQL
