x-afisha-depends-on: &afisha-depends-on
  db:
    condition: service_healthy
  payment:
    condition: service_healthy
  protection:
    condition: service_healthy
  redis:
    condition: service_healthy
  afisha-migrations:
    condition: service_completed_successfully

x-afisha-db-environment: &afisha-db-environment
  DB__HOST: db
  DB__PORT: 5432
  DB__USER: $AFISHA_DB_USER
  DB__PASS: $AFISHA_DB_PASS
  DB__NAME: $AFISHA_DB_NAME

x-redis-environment: &redis-environment
  REDIS__HOST: redis
  REDIS__PORT: 6379
  REDIS__DB_NUMBER: 0

x-payment-environment: &payment-environment
  PAYMENT__HOST: payment
  PAYMENT__PROTO: http
  PAYMENT__PORT: 8000

x-protection-environment: &protection-environment
  PROTECTION__HOST: protection
  PROTECTION__PROTO: http
  PROTECTION__PORT: 8000

x-kafka-environment: &kafka-environment
  KAFKA__BOOTSTRAP_SERVERS: kafka:9091
  KAFKA__TICKETS_TOPIC: tickets.purchased

services:
  db:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      AFISHA_DB_NAME: $AFISHA_DB_NAME
      AFISHA_DB_USER: $AFISHA_DB_USER
      AFISHA_DB_PASS: $AFISHA_DB_PASS
      PURCHASED_TICKETS_DB_NAME: $PURCHASED_TICKETS_DB_NAME
      PURCHASED_TICKETS_DB_USER: $PURCHASED_TICKETS_DB_USER
      PURCHASED_TICKETS_DB_PASS: $PURCHASED_TICKETS_DB_PASS
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment:
    build: ./mock_apis/payment
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  protection:
    build: ./mock_apis/protection
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:4.3.1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://localhost:9093,EXTERNAL://:9092,INTERNAL://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092,INTERNAL://kafka:9091
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
    healthcheck:
      test: /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:29092 --list
      interval: 15s
      timeout: 10s
      retries: 3

  kafka-init:
    image: apache/kafka:4.3.1
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic tickets.purchased --partitions 2 --replication-factor 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      KAFKA_CLUSTERS_0_NAME: afisha
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_healthy

  afisha-migrations:
    build: ./afisha
    entrypoint: ["alembic", "upgrade", "head"]
    restart: "no"
    environment:
      <<: [*afisha-db-environment]
    depends_on:
      db:
        condition: service_healthy

  afisha-scheduler:
    build: ./afisha
    entrypoint:
      - taskiq
      - scheduler
      - src.infrastracture.tasks.app:scheduler
      - src.infrastracture.tasks.tasks
      - --log-level
      - INFO
    environment:
      <<: [*redis-environment]
    depends_on: *afisha-depends-on

  afisha-worker-sync:
    build: ./afisha
    entrypoint:
      - taskiq
      - worker
      - src.infrastracture.tasks.app:broker_sync
      - src.infrastracture.tasks.tasks
    environment:
      <<: [*afisha-db-environment, *redis-environment, *payment-environment, *protection-environment, *kafka-environment]
    depends_on: *afisha-depends-on

  afisha-worker-async:
    build: ./afisha
    entrypoint:
      - taskiq
      - worker
      - src.infrastracture.tasks.app:broker_async
      - src.infrastracture.tasks.tasks
    environment:
      <<: [*afisha-db-environment, *redis-environment, *payment-environment, *protection-environment, *kafka-environment]
    depends_on: *afisha-depends-on

  afisha:
    build: ./afisha
    environment:
      <<: [*afisha-db-environment, *redis-environment, *payment-environment, *protection-environment, *kafka-environment]
    ports:
      - 9000:8000
    depends_on: *afisha-depends-on
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/openapi.json"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
