x-afisha-depends-on: &afisha-depends-on
  db:
    condition: service_healthy
  payment:
    condition: service_healthy
  protection:
    condition: service_healthy
  redis:
    condition: service_healthy
  afisha-migrations:
    condition: service_completed_successfully

x-db-environment: &db-environment
  DB__HOST: db
  DB__PORT: 5432
  DB__USER: $DB_USER
  DB__PASS: $DB_PASS
  DB__NAME: $DB_NAME

x-redis-environment: &redis-environment
  REDIS__HOST: redis
  REDIS__PORT: 6379
  REDIS__DB_NUMBER: 0

x-payment-environment: &payment-environment
  PAYMENT__HOST: payment
  PAYMENT__PROTO: http
  PAYMENT__PORT: 8000

x-protection-environment: &protection-environment
  PROTECTION__HOST: protection
  PROTECTION__PROTO: http
  PROTECTION__PORT: 8000

services:
  db:
    image: postgres:18-trixie
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment:
    build: ./mock_apis/payment
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  protection:
    build: ./mock_apis/protection
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  afisha-migrations:
    build: ./afisha
    entrypoint: ["alembic", "upgrade", "head"]
    restart: "no"
    environment:
      <<: [*db-environment]
    depends_on:
      db:
        condition: service_healthy

  afisha-scheduler:
    build: ./afisha
    entrypoint:
      - taskiq
      - scheduler
      - src.infrastracture.tasks.app:scheduler
      - src.infrastracture.tasks.tasks
      - --log-level
      - INFO
    environment:
      <<: [*redis-environment]
    depends_on: *afisha-depends-on

  afisha-worker-sync:
    build: ./afisha
    entrypoint:
      - taskiq
      - worker
      - src.infrastracture.tasks.app:broker_sync
      - src.infrastracture.tasks.tasks
    environment:
      <<: [*db-environment, *redis-environment, *payment-environment, *protection-environment]
    depends_on: *afisha-depends-on

  afisha-worker-async:
    build: ./afisha
    entrypoint:
      - taskiq
      - worker
      - src.infrastracture.tasks.app:broker_async
      - src.infrastracture.tasks.tasks
    environment:
      <<: [*db-environment, *redis-environment, *payment-environment, *protection-environment]
    depends_on: *afisha-depends-on

  afisha:
    build: ./afisha
    environment:
      <<: [*db-environment, *redis-environment, *payment-environment, *protection-environment]
    ports:
      - 9000:8000
    depends_on: *afisha-depends-on
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:8000/openapi.json"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
