on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: afisha
            working-directory: week2/afisha
          - name: payment
            working-directory: week2/mock_apis/payment
          - name: protection
            working-directory: week2/mock_apis/protection
          - name: purchased_tickets
            working-directory: week2/purchased_tickets
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Python init
        uses: ./.github/python

      - name: Ruff linting
        run: uv run ruff check
        working-directory: ${{ matrix.service.working-directory }}

      - name: Ruff formatting
        run: uv run ruff format --check
        working-directory: ${{ matrix.service.working-directory }}

      - name: Check types
        run: uv run ty check
        working-directory: ${{ matrix.service.working-directory }}
